### ISSUE TITLE
HTTP 505 when running "php octo octopus/import"

### ISSUE THREAD

**Issue by NiccyB** [hypercrypt/octopus-db#7]
Hi,

Running:
`php octo octopus/import`
generates the following:
```
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ServerException: Server error: `GET https://api.octopus.energy/v1/accounts/XXXXXXXX` resulted in a `505 HTTP Version Not Supported` response:
<html>
<head><title>505 HTTP Version Not Supported</title></head>
<body>
<center><h1>505 HTTP Version Not Supported</ (truncated...)
 in /home/nicholas/octopus-db/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /home/nicholas/octopus-db/vendor/guzzlehttp/guzzle/src/Middleware.php(69): GuzzleHttp\Exception\RequestException::create()
#1 /home/nicholas/octopus-db/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#2 /home/nicholas/octopus-db/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler()
#3 /home/nicholas/octopus-db/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /home/nicholas/octopus-db/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Promise\TaskQueue->run()
#5 /home/nicholas/octopus-db/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 /home/nicholas/octopus-db/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()
#7 /home/nicholas/octopus-db/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 /home/nicholas/octopus-db/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /home/nicholas/octopus-db/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Promise\Promise->wait()
#10 /home/nicholas/octopus-db/vendor/guzzlehttp/guzzle/src/ClientTrait.php(44): GuzzleHttp\Client->request()
#11 /home/nicholas/octopus-db/classes/OctopusEnergy.php(96): GuzzleHttp\Client->get()
#12 /home/nicholas/octopus-db/classes/OctopusEnergy.php(24): OctopusEnergy->fetch_json()
#13 /home/nicholas/octopus-db/scripts/octopus/import.php(7): OctopusEnergy->__construct()
#14 /home/nicholas/octopus-db/octo(31): require_once('...')
#15 {main}
  thrown in /home/nicholas/octopus-db/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113

Fatal error: Uncaught GuzzleHttp\Exception\ServerException: Server error: `GET https://api.octopus.energy/v1/accounts/A-` resulted in a `505 HTTP Version Not Supported` response:
<html>
<head><title>505 HTTP Version Not Supported</title></head>
<body>
<center><h1>505 HTTP Version Not Supported</ (truncated...)
 in /home/nicholas/octopus-db/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /home/nicholas/octopus-db/vendor/guzzlehttp/guzzle/src/Middleware.php(69): GuzzleHttp\Exception\RequestException::create()
#1 /home/nicholas/octopus-db/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#2 /home/nicholas/octopus-db/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler()
#3 /home/nicholas/octopus-db/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /home/nicholas/octopus-db/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Promise\TaskQueue->run()
#5 /home/nicholas/octopus-db/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 /home/nicholas/octopus-db/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()
#7 /home/nicholas/octopus-db/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 /home/nicholas/octopus-db/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /home/nicholas/octopus-db/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Promise\Promise->wait()
#10 /home/nicholas/octopus-db/vendor/guzzlehttp/guzzle/src/ClientTrait.php(44): GuzzleHttp\Client->request()
#11 /home/nicholas/octopus-db/classes/OctopusEnergy.php(96): GuzzleHttp\Client->get()
#12 /home/nicholas/octopus-db/classes/OctopusEnergy.php(24): OctopusEnergy->fetch_json()
#13 /home/nicholas/octopus-db/scripts/octopus/import.php(7): OctopusEnergy->__construct()
#14 /home/nicholas/octopus-db/octo(31): require_once('...')
#15 {main}
  thrown in /home/nicholas/octopus-db/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113
```

**Comment by NiccyB** [comment]
The same error occurs when "php octo bright/import" is run.

**Comment by NiccyB** [comment]
And also the deprecated "php octopus.php", so no imports are currently working.

**Comment by hypercrypt** [comment]
Could you check if the new fix works for you please?

```
git fetch
git checkout issue/7
```

After you're done and I've pushed my fix you can

```
git checkout main
git pull
```

**Comment by hypercrypt** [comment]
Sorry, issue should indeed be issues, have edited my message above to correct the typo.

If you have a look at the sample config file there are a few new keys around e7 but will fix this issue as well. Have opened #8  for it

**Comment by NiccyB** [comment]
Hi,
I can't see anything e7 related in the sample config file. My config has the same layout as the sample except the gas resource ID for bright isn't there (we don't have gas here).
